-- ============================================================
-- RLS Hardening: newsletter_subscribers + tenant-documents storage
-- ============================================================
-- Run this after migration_property_news.sql

-- ── newsletter_subscribers ──────────────────────────────────
-- The original migration set "for all using (true)" which
-- allows any anonymous caller to read, update or delete any
-- subscriber row.  Replace with tighter per-operation policies.

alter table public.newsletter_subscribers enable row level security;

-- Drop the overly-permissive catch-all policy
drop policy if exists "subscribers manage own record" on public.newsletter_subscribers;
drop policy if exists "newsletter_subscribers_all_public" on public.newsletter_subscribers;

-- Public INSERT only — anyone may subscribe
create policy "newsletter_subscribers_insert_public"
  on public.newsletter_subscribers
  for insert
  with check (true);

-- No SELECT / UPDATE / DELETE via the anon key at all.
-- All read/write access goes through the service-role API routes
-- (subscribe, unsubscribe, resubscribe, digest-sender).

-- ── property_news_send_log ──────────────────────────────────
-- Only service role should write; no public read needed.
alter table public.property_news_send_log enable row level security;
drop policy if exists "send_log_public_read" on public.property_news_send_log;

-- ── tenant-documents storage bucket ─────────────────────────
-- Uploads go through the API (service-role bypass is fine).
-- Prevent direct public downloads — only signed URLs work.
-- Run in Supabase Dashboard > Storage > Policies if the bucket exists.
--
-- NOTE: Storage bucket policies cannot be created via SQL migrations in the
-- same way as table RLS.  Apply the following in the Supabase Dashboard:
--
--   Bucket: tenant-documents
--   Policy name: service_role_only_upload
--   Operation: INSERT
--   Definition: (auth.role() = 'service_role')
--
--   Policy name: no_public_download
--   Operation: SELECT
--   Definition: (auth.role() = 'service_role')
--
-- Signed URLs generated by the API (createSignedUrl) are unaffected.
