// ─── Mock property data ───────────────────────────────────────────────────────
// Used when no real properties are listed in the database.
// Swap out by removing the `isDemo` branch in page.tsx and connecting real data.

import type { PropertyData } from "@/lib/scoring/interest-engine";

// Slim shape used for display — parallels a Supabase properties row
export type PropertyWithMeta = {
  id: string;
  name: string;
  suburb: string | null;
  province: string | null;
  rent: number; // ZAR/month
  bedrooms: number | null;
  property_type: string | null;
  photos: string[];
  available_from: string | null;
  pets_allowed: boolean;
};

// ─── Scoring data (PropertyData shape) ───────────────────────────────────────
// These are used by the interest engine to produce match scores + reasons.
// Rich enough to exercise all 8 scoring dimensions.

export const MOCK_PROPERTY_SCORING_DATA: PropertyData[] = [
  {
    property_id: "mock-01",
    title: "Bright 2-bed apartment, Sea Point",
    suburb: "Sea Point",
    rent: 11000,
    bedrooms: 2,
    property_tags: ["apartment", "fibre_available", "building_security"],
    area_tags: ["beach_access", "walkable", "public_transport"],
    lifestyle_tags: ["outdoor_lifestyle", "coffee_culture", "restaurant_scene"],
    pets_allowed: false,
    parking_available: false,
    fibre_available: true,
    building_security_score: 8,
    suburb_avg_rent: 14500,
    crime_index: 42,
    applications_count: 3,
    walkability_score: 9,
    public_transport_score: 7,
    minutes_to_coffee: 3,
    minutes_to_gym: 8,
    minutes_to_park: 5,
    minutes_to_restaurant: 2,
    social_life_score: 8,
    outdoor_lifestyle_score: 9,
    remote_work_score: 7,
    estimated_electricity: 1200,
    estimated_water: 300,
    estimated_internet: 700,
  },
  {
    property_id: "mock-02",
    title: "Sunny 2-bed flat, Green Point",
    suburb: "Green Point",
    rent: 13000,
    bedrooms: 2,
    property_tags: ["apartment", "fibre_available", "building_security", "parking"],
    area_tags: ["beach_access", "walkable"],
    lifestyle_tags: ["outdoor_lifestyle", "coffee_culture"],
    pets_allowed: false,
    parking_available: true,
    fibre_available: true,
    building_security_score: 7,
    suburb_avg_rent: 14000,
    crime_index: 38,
    applications_count: 4,
    walkability_score: 8,
    public_transport_score: 7,
    minutes_to_coffee: 5,
    minutes_to_gym: 10,
    minutes_to_park: 8,
    minutes_to_restaurant: 4,
    social_life_score: 7,
    outdoor_lifestyle_score: 8,
    remote_work_score: 7,
    estimated_electricity: 1200,
    estimated_water: 300,
    estimated_internet: 700,
  },
  {
    property_id: "mock-03",
    title: "Spacious 2-bed, Vredehoek",
    suburb: "Vredehoek",
    rent: 11500,
    bedrooms: 2,
    property_tags: ["apartment", "fibre_available", "building_security"],
    area_tags: ["walkable", "quiet_suburb"],
    lifestyle_tags: ["outdoor_lifestyle", "remote_work"],
    pets_allowed: true,
    parking_available: true,
    fibre_available: true,
    building_security_score: 7,
    suburb_avg_rent: 13000,
    crime_index: 22,
    applications_count: 1,
    walkability_score: 7,
    public_transport_score: 5,
    minutes_to_coffee: 7,
    minutes_to_gym: 12,
    minutes_to_park: 3,
    minutes_to_restaurant: 8,
    social_life_score: 4,
    outdoor_lifestyle_score: 9,
    remote_work_score: 9,
    estimated_electricity: 1200,
    estimated_water: 300,
    estimated_internet: 700,
  },
  {
    property_id: "mock-04",
    title: "Modern 1-bed, Gardens",
    suburb: "Gardens",
    rent: 9000,
    bedrooms: 1,
    property_tags: ["apartment", "fibre_available"],
    area_tags: ["walkable", "public_transport"],
    lifestyle_tags: ["coffee_culture", "remote_work"],
    pets_allowed: false,
    parking_available: false,
    fibre_available: true,
    building_security_score: 6,
    suburb_avg_rent: 11000,
    crime_index: 34,
    applications_count: 5,
    walkability_score: 8,
    public_transport_score: 7,
    minutes_to_coffee: 4,
    minutes_to_gym: 10,
    minutes_to_park: 6,
    minutes_to_restaurant: 5,
    social_life_score: 7,
    outdoor_lifestyle_score: 6,
    remote_work_score: 8,
    estimated_electricity: 900,
    estimated_water: 250,
    estimated_internet: 700,
  },
  {
    property_id: "mock-05",
    title: "Open-plan 2-bed loft, Woodstock",
    suburb: "Woodstock",
    rent: 10000,
    bedrooms: 2,
    property_tags: ["apartment", "fibre_available"],
    area_tags: ["public_transport", "walkable"],
    lifestyle_tags: ["coffee_culture", "remote_work"],
    pets_allowed: false,
    parking_available: false,
    fibre_available: true,
    building_security_score: 5,
    suburb_avg_rent: 11000,
    crime_index: 68,
    applications_count: 6,
    walkability_score: 7,
    public_transport_score: 8,
    minutes_to_coffee: 5,
    minutes_to_gym: 14,
    minutes_to_park: 10,
    minutes_to_restaurant: 5,
    social_life_score: 8,
    outdoor_lifestyle_score: 5,
    remote_work_score: 9,
    estimated_electricity: 1100,
    estimated_water: 300,
    estimated_internet: 700,
  },
  {
    property_id: "mock-06",
    title: "3-bed family home, Bellville",
    suburb: "Bellville",
    rent: 8500,
    bedrooms: 3,
    property_tags: ["house", "parking"],
    area_tags: ["schools"],
    lifestyle_tags: [],
    pets_allowed: true,
    parking_available: true,
    fibre_available: false,
    building_security_score: 5,
    suburb_avg_rent: 9000,
    crime_index: 48,
    applications_count: 2,
    walkability_score: 5,
    public_transport_score: 5,
    minutes_to_coffee: 18,
    minutes_to_gym: 22,
    minutes_to_park: 14,
    minutes_to_restaurant: 15,
    social_life_score: 4,
    outdoor_lifestyle_score: 4,
    remote_work_score: 5,
    estimated_electricity: 1400,
    estimated_water: 350,
    estimated_internet: 0,
  },
];

// ─── Display metadata (for the card UI) ──────────────────────────────────────
// IDs match MOCK_PROPERTY_SCORING_DATA so they can be joined in the client.

export const MOCK_PROPERTY_META: PropertyWithMeta[] = [
  {
    id: "mock-01",
    name: "Bright 2-bed apartment, Sea Point",
    suburb: "Sea Point",
    province: "Western Cape",
    rent: 11000,
    bedrooms: 2,
    property_type: "apartment",
    photos: [],
    available_from: "2026-07-01",
    pets_allowed: false,
  },
  {
    id: "mock-02",
    name: "Sunny 2-bed flat, Green Point",
    suburb: "Green Point",
    province: "Western Cape",
    rent: 13000,
    bedrooms: 2,
    property_type: "apartment",
    photos: [],
    available_from: "2026-07-15",
    pets_allowed: false,
  },
  {
    id: "mock-03",
    name: "Spacious 2-bed, Vredehoek",
    suburb: "Vredehoek",
    province: "Western Cape",
    rent: 11500,
    bedrooms: 2,
    property_type: "apartment",
    photos: [],
    available_from: "2026-08-01",
    pets_allowed: true,
  },
  {
    id: "mock-04",
    name: "Modern 1-bed, Gardens",
    suburb: "Gardens",
    province: "Western Cape",
    rent: 9000,
    bedrooms: 1,
    property_type: "apartment",
    photos: [],
    available_from: "2026-07-01",
    pets_allowed: false,
  },
  {
    id: "mock-05",
    name: "Open-plan 2-bed loft, Woodstock",
    suburb: "Woodstock",
    province: "Western Cape",
    rent: 10000,
    bedrooms: 2,
    property_type: "apartment",
    photos: [],
    available_from: "2026-07-01",
    pets_allowed: false,
  },
  {
    id: "mock-06",
    name: "3-bed family home, Bellville",
    suburb: "Bellville",
    province: "Western Cape",
    rent: 8500,
    bedrooms: 3,
    property_type: "house",
    photos: [],
    available_from: "2026-08-01",
    pets_allowed: true,
  },
];
